"""Script to initialize the FAISS vector database with sample knowledge."""
import os
import sys

# Add the parent directory to the path so we can import from services
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from services.vector_db import VectorDBService

def create_sample_schema():
    """Create a sample db_schema.txt file if it doesn't exist."""
    knowledge_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "knowledge")
    os.makedirs(knowledge_dir, exist_ok=True)
    
    schema_path = os.path.join(knowledge_dir, "db_schema.txt")
    
    # Only create if it doesn't exist
    if not os.path.exists(schema_path):
        print(f"Creating sample schema file at {schema_path}")
        
        with open(schema_path, "w") as f:
            f.write("""# AI Database Assistant Schema

This document describes the database schema for the AI Database Assistant application.

## System Tables

### SQLHistory Table
Stores the history of SQL queries generated by the AI assistant.

Columns:
- id (Integer, Primary Key): Unique identifier for each history entry
- description (Text): Natural language description of what the SQL should do
- dialect (String): SQL dialect used (e.g., MySQL, PostgreSQL)
- generated_sql (Text): The SQL query generated by the AI
- timestamp (DateTime): When the SQL was generated

### ChatHistory Table
Stores conversation history between users and the AI assistant.

Columns:
- id (Integer, Primary Key): Unique identifier for each chat history entry
- conversation_id (String): Unique identifier for the conversation
- messages (Text): JSON string containing all messages in the conversation
- title (String): Optional title for the conversation
- created_at (DateTime): When the conversation was created
- updated_at (DateTime): When the conversation was last updated

## Common SQL Queries

### Get Recent SQL History
```sql
SELECT id, description, dialect, generated_sql, timestamp
FROM sql_history
ORDER BY timestamp DESC
LIMIT 10;
```

### Search SQL History by Description
```sql
SELECT id, description, dialect, generated_sql, timestamp
FROM sql_history
WHERE description LIKE '%search_term%'
ORDER BY timestamp DESC;
```

### Get Chat History by Conversation ID
```sql
SELECT id, conversation_id, messages, title, created_at, updated_at
FROM chat_history
WHERE conversation_id = 'specific_conversation_id';
```
""")
        print("Sample schema file created successfully!")
    else:
        print(f"Schema file already exists at {schema_path}")

def main():
    """Initialize the FAISS vector database."""
    print("Initializing FAISS vector database...")
    
    # Create sample schema if it doesn't exist
    create_sample_schema()
    
    # Initialize vector database
    vector_db = VectorDBService()
    
    # Force reindex
    success = vector_db.clear_and_reindex()
    
    if success:
        print("\nFAISS vector database initialized successfully!")
        print(f"Database stored at: {os.path.abspath(vector_db.index_path)}")
    else:
        print("\nFailed to initialize FAISS vector database.")

if __name__ == "__main__":
    main()